/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        blush: {
          50: '#fdf2f4',
          100: '#fce7eb',
          200: '#f9d0d9',
          300: '#f4aab9',
          400: '#ec7a94',
          500: '#e05277',
          600: '#cd335f',
          700: '#ac254c',
          800: '#8f2243',
          900: '#7a203d',
        },
        sage: {
          50: '#f4f7f4',
          100: '#e3ebe3',
          200: '#c5d8c5',
          300: '#9bbd9b',
          400: '#729c72',
          500: '#528152',
          600: '#3e653e',
          700: '#335133',
          800: '#2b412b',
          900: '#243624',
        },
        cream: {
          50: '#fdfcfa',
          100: '#faf6f0',
          200: '#f5ede3',
          300: '#ede0d0',
          400: '#e0c9b0',
          500: '#d4b08e',
          600: '#c9966e',
          700: '#a87652',
          800: '#8a6246',
          900: '#70513d',
        },
        lavender: {
          50: '#f9f7fb',
          100: '#f2eef7',
          200: '#e7dfef',
          300: '#d6c6e2',
          400: '#bea5d0',
          500: '#a582bc',
          600: '#8b64a3',
          700: '#745186',
          800: '#60446e',
          900: '#50395a',
        },
        champagne: {
          50: '#fcfbf9',
          100: '#f9f6f0',
          200: '#f3ede3',
          300: '#ebe0d0',
          400: '#dcc9b0',
          500: '#cbb08e',
          600: '#b8966e',
          700: '#997752',
          800: '#7f6246',
          900: '#67513d',
        },
      },
      fontFamily: {
        script: ['Great Vibes', 'cursive'],
        serif: ['Playfair Display', 'serif'],
        body: ['Cormorant Garamond', 'serif'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        soft: "0 4px 20px rgba(0, 0, 0, 0.06)",
        elegant: "0 8px 32px rgba(0, 0, 0, 0.08)",
        glow: "0 0 30px rgba(212, 165, 165, 0.3)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-15px)" },
        },
        "float-slow": {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%": { transform: "translateY(-10px) rotate(2deg)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.85", transform: "scale(1.03)" },
        },
        "fade-in-up": {
          "from": { opacity: "0", transform: "translateY(30px)" },
          "to": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "from": { opacity: "0" },
          "to": { opacity: "1" },
        },
        "scale-in": {
          "from": { opacity: "0", transform: "scale(0.9)" },
          "to": { opacity: "1", transform: "scale(1)" },
        },
        "slide-in-right": {
          "from": { opacity: "0", transform: "translateX(50px)" },
          "to": { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-left": {
          "from": { opacity: "0", transform: "translateX(-50px)" },
          "to": { opacity: "1", transform: "translateX(0)" },
        },
        "petal-fall": {
          "0%": { transform: "translateY(-10px) rotate(0deg)", opacity: "1" },
          "100%": { transform: "translateY(100vh) rotate(360deg)", opacity: "0" },
        },
        "sparkle": {
          "0%, 100%": { opacity: "0", transform: "scale(0)" },
          "50%": { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "float": "float 6s ease-in-out infinite",
        "float-slow": "float-slow 8s ease-in-out infinite",
        "pulse-soft": "pulse-soft 3s ease-in-out infinite",
        "fade-in-up": "fade-in-up 1s ease-out forwards",
        "fade-in": "fade-in 1.2s ease-out forwards",
        "scale-in": "scale-in 0.8s ease-out forwards",
        "slide-in-right": "slide-in-right 1s ease-out forwards",
        "slide-in-left": "slide-in-left 1s ease-out forwards",
        "petal-fall": "petal-fall 8s linear infinite",
        "sparkle": "sparkle 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
