/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        chocolate: {
          50: '#faf6f2',
          100: '#f2e8de',
          200: '#e6d0bf',
          300: '#d4b095',
          400: '#c08a6a',
          500: '#a86b48',
          600: '#8a5238',
          700: '#6d402f',
          800: '#5a362a',
          900: '#4a2e26',
          950: '#2a1812',
        },
        mocha: {
          50: '#faf7f4',
          100: '#f2ebe3',
          200: '#e5d6c5',
          300: '#d4b99b',
          400: '#c39a72',
          500: '#b58152',
          600: '#a06a42',
          700: '#855336',
          800: '#6f4532',
          900: '#5a3a2d',
        },
        cappuccino: {
          50: '#fbf9f6',
          100: '#f5f0e8',
          200: '#ebe0cf',
          300: '#dec5ad',
          400: '#cea585',
          500: '#c08862',
          600: '#a86d4b',
          700: '#8a573d',
          800: '#724835',
          900: '#5d3d2f',
        },
        cream: {
          50: '#fdfcfa',
          100: '#faf6f0',
          200: '#f5ede3',
          300: '#ede0d0',
          400: '#e0c9b0',
          500: '#d4b08e',
          600: '#c9966e',
          700: '#a87652',
          800: '#8a6246',
          900: '#70513d',
        },
        gold: {
          50: '#fbf9f0',
          100: '#f5f0de',
          200: '#ebe0bc',
          300: '#dec992',
          400: '#d4b06a',
          500: '#c99645',
          600: '#b57d38',
          700: '#96622f',
          800: '#7d4f2c',
          900: '#664127',
        },
        pearl: {
          50: '#fdfcfb',
          100: '#faf8f5',
          200: '#f5f0ea',
          300: '#ebe4da',
          400: '#e0d5c5',
          500: '#d4c4ae',
          600: '#c4b096',
          700: '#a8947d',
          800: '#8a7a68',
          900: '#706455',
        },
      },
      fontFamily: {
        script: ['Great Vibes', 'cursive'],
        serif: ['Playfair Display', 'serif'],
        body: ['Cormorant Garamond', 'serif'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        soft: "0 4px 20px rgba(0, 0, 0, 0.06)",
        elegant: "0 8px 32px rgba(0, 0, 0, 0.08)",
        glow: "0 0 30px rgba(168, 107, 72, 0.3)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-15px)" },
        },
        "float-slow": {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%": { transform: "translateY(-10px) rotate(2deg)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.85", transform: "scale(1.03)" },
        },
        "fade-in-up": {
          "from": { opacity: "0", transform: "translateY(30px)" },
          "to": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "from": { opacity: "0" },
          "to": { opacity: "1" },
        },
        "scale-in": {
          "from": { opacity: "0", transform: "scale(0.9)" },
          "to": { opacity: "1", transform: "scale(1)" },
        },
        "slide-in-right": {
          "from": { opacity: "0", transform: "translateX(50px)" },
          "to": { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-left": {
          "from": { opacity: "0", transform: "translateX(-50px)" },
          "to": { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "float": "float 6s ease-in-out infinite",
        "float-slow": "float-slow 8s ease-in-out infinite",
        "pulse-soft": "pulse-soft 3s ease-in-out infinite",
        "fade-in-up": "fade-in-up 1s ease-out forwards",
        "fade-in": "fade-in 1.2s ease-out forwards",
        "scale-in": "scale-in 0.8s ease-out forwards",
        "slide-in-right": "slide-in-right 1s ease-out forwards",
        "slide-in-left": "slide-in-left 1s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
